package com.common.project.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.common.project.entity.NewWordEntity;

import com.common.project.greendao.NewWordEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newWordEntityDaoConfig;

    private final NewWordEntityDao newWordEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newWordEntityDaoConfig = daoConfigMap.get(NewWordEntityDao.class).clone();
        newWordEntityDaoConfig.initIdentityScope(type);

        newWordEntityDao = new NewWordEntityDao(newWordEntityDaoConfig, this);

        registerDao(NewWordEntity.class, newWordEntityDao);
    }
    
    public void clear() {
        newWordEntityDaoConfig.clearIdentityScope();
    }

    public NewWordEntityDao getNewWordEntityDao() {
        return newWordEntityDao;
    }

}
